[package]
name = "smartcore-example"
version = "0.1.0"
edition = "2018"

[dependencies]
smartcore = { version = "0.2.0", default-features = false, features=["nalgebra-bindings", "ndarray-bindings", "datasets"]}
